### PR TITLE
allow to plug in to ConfigurableData with afterAddData plugin method …

### PR DESCRIPTION
**Pull request by janmyszkier**
…by allowing to reuse the ConfigurableData properties when adding own custom index data

The point of this PR is to allow using magento after/before hooks and reuse the `$subject` properties to modify the data before they are pushed to ES

Example of such implementation has been added here:
https://github.com/coding-mice/magento2-vsbridge-indexer-extension

### CODE REVIEW

**Comment by janmyszkier** [comment]
@afirlejczyk I believe this should be done for all the models to allow easier extension 
This way (comparing to using `preference`) will allow to not focus on logic modifications but data manipulation which is what people are usually after when adding custom ES data.

**Comment by pablogiralt** [comment]
This is a great contribution by @janmyszkier and would be great to have it merged.  We are currently using a fork of this repo with jan's pull request merged in our project.

**Comment by janmyszkier** [comment]
rebase done

**Comment by janmyszkier** [comment]
I see a bigger update has been pushed and rebase just makes this unreadable so I'll also create a new PR

**Comment by afirlejczyk** [comment]
Hello,

As I mention here: https://github.com/DivanteLtd/magento2-vsbridge-indexer/issues/198 
I don't plan to expose constructor properties.

We have different options to extended exported data to ES.

- you can use plugin and Interfaces to make required customization.
In one of the latest requests (https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/216) I did some small refactoring. I added new interfaces - so user can relay on them.

- you add custom `data_provider` in `vsbridge_indices.xml` configuration (and use interfaces if needed).
Example: https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/220 - here I add new data provider for "attributes_metadata"

- you can override default configuration for "configurable_data" dataprovider

If some interfaces are missing I would create issue for that - then we can do some more refactoring in core module - add new interfaces that might be useful for others.

The module architecture is not perfect and require some time to re-design. I have very little time for it (if any) in my spare time, the structure might changed someday but I wouldn't expect it soon.

Still, you can easily add:
- new dataproviders to extended existing types
- create new indexers to export new types to ES

**Pull request closed without merging**
