### PR TITLE
Add Elasticsearch index version support using aliases

### PR DESCRIPTION
**Pull request by yuriboyko**
In case of changing mapping for some attributes current  indexer functionality support only delete index and create new one. But for live inviromnet is important to not have index be deleted. So the best way for this use indexe with versions and alias. in this case product export  processes to the new index created  and changes alias at the end.

### CODE REVIEW

**Comment by afirlejczyk** [comment]
Thanks for this PR, I will checkout it out!

I though about different approach regarding aliases, so I need some time to verify this.
I can't share my idea yet, because my solution is not fully formed.

**Comment by yuriboyko** [comment]
Hi @afirlejczyk  could you provide some info on the reason why the PR is closed

**Comment by afirlejczyk** [comment]
Hi @yuriboyko, as I wrote before, I had a different concept for supporting aliases.
I created new PR for this: https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/131
It will be merged to develop shortly.

**Comment by afirlejczyk** [comment]
+ small fixes https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/138

**Pull request closed without merging**
