### PR TITLE
Support for ES 6+.

### PR DESCRIPTION
**Pull request by afirlejczyk**
Details: DivanteLtd/vue-storefront#1692
#134

TODO
- [ ] Upgrade note from `1.*` to `2.*` version
- [ ] Contribution guide

### CODE REVIEW

**Comment by pkarw** [comment]
@afirlejczyk what's the status of this PR? I mean is there anything specific that needs to be implemented, we need some QA? How does it look like?

**Comment by thampe** [comment]
Hi,

do you know when/if this PR will be merged?

Thanks in Advance.

**Comment by afirlejczyk** [comment]
Hi, 
It will be merged to branch 2.x soon.
I didn't finish writing upgrade notes for developers (if they decide to switch to ES 6+, they will have to update their extension) and add some information about contributions.
We will have 2 main branches `1.x` (for ES 5 support) and `2.x` for (ES 6+) support.

I wanted to merge it when I will be done with that, but I think I will merge changes tomorrow and add missing information later.

**Comment by thampe** [comment]
Hi,

thanks for the info!

**Comment by neticon-polovina** [comment]
Hi guys. Are you planning QA on this feature (branch 2.x)? Is it solid enough to have it in production

**Comment by afirlejczyk** [comment]
Update (22.04.2020)
After given some toughs and keeping branch 2.x up to date,
I plan to have support for ES5 and ES6+ on the same branch. So we won't have two main branches.

I am working on some changes in core to make it happen. I will give an update when it will be done (there will be new release version 2.0.0).

I won't be updating 2.x branch anymore, I will leave it as it is.
Configuration will change a little for ES5 and ES6+.

**Comment by simonmaass** [comment]
@afirlejczyk so support for ES7 (as VSF 1.11 also has ES7 support) will be coming in 2.0? do you have any timeframe for when 2.0 will be released?

**Comment by afirlejczyk** [comment]
I don't, you can use `2.x` branch for now.. (support for ES7 is working there) I can also make a version for it: `2.0.0-alpha`.

In changes I am working - there will be a little different configuration - but nothing painful to update..  I hope.

**Comment by one1note** [comment]
Do you already have a 2.0.0-alpha release that I can add via composer?

**Comment by afirlejczyk** [comment]
2.0-alpha release is now available.

**Comment by jonathanribas** [comment]
Hi, we are experiencing big issues with ES 5.x (managed service) in production with GC / CPU spikes to 100% that creates downtimes. We can't reproduce this issue locally as it needs a real environment with reindexations running, real traffic searching...

We want to move to ES 7.x hoping it gets sorted.

Do you have a plan to make 2.0 branch stable?

Thanks in advance.

**Comment by afirlejczyk** [comment]
I worked on solution to make it work both with ES 5.x and higher versions (ES 6.X and ES 7.X)
Today I merged changes to develop branch, few thinks left for me to do:
- how to make an upgrade from 1.x to 2.x (there are few changes how types and data providers are declared in xml)
So I want to provide a small example what changed.
- release not

In short what changed:
- you have to choose ES version in configuration (by default ES5 is selected)
- `vsbridge_indexer.xml` was replaced with `vsbridge.xml`, you only declare type/entity and mapping
- Dataproviders configuration was moved to `di.xml`
- for ES 5 only one index is created, for ES6+ we have separated indices per type

**Comment by afirlejczyk** [comment]
Hi @simonmaass 
Do you have time to checkout changes in develop branch? if not could you checkout if export to ES5 and ES6+ works as expected? I make some changes, cleanup past weeks. 
Small info about release available here: https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/345

I open to here some feedback, so I can merge this and make official release.  

Thank you,
Agata

**Comment by simonmaass** [comment]
hey @afirlejczyk we are currently running the 2.0 develop version in production... we have magento 2.4 with php7 and are using ES7.... everything works as expected.... i cannot say anything to ES5 or ES6...

**Comment by afirlejczyk** [comment]
Hey, you mean you are using changes from 2.x branch/2.0-alpha? This I know it works.:)

I would appreciate if anyone can check new changes: https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/336 
which are available in develop branch. 
Few thinks had change: https://github.com/DivanteLtd/magento2-vsbridge-indexer/pull/345

If no one will be able to verify it I will merge it as it is to master branch.

**Comment by simonmaass** [comment]
@afirlejczyk sorry - will not be able to verify any time soon - but i would go ahead an merge to master, as many people are waiting for a stable es6+ version

**Pull request merged**
