### PR TITLE
Product and category url_path - export with suffixes.

### PR DESCRIPTION
**Pull request by afirlejczyk**

### CODE REVIEW

**Comment by domideimel** [comment]
Can you merge this feature with your 2.x Branch as well? or has the develop branch support for es 6+ as well?

**Comment by afirlejczyk** [comment]
Yes, I will update `2.x` branch on Monday/Tuesday.

**Comment by afirlejczyk** [comment]
Branch `2.x` was updated.

**Comment by domideimel** [comment]
Ty

**Pull request merged**
